### ISSUE TITLE
running command "harness-cli train test_ur" throws error

### ISSUE THREAD

**Issue by ghost** [actionml/harness#200]
## System
- using ubuntu 18.04
- 16 GB ram
- 512 SSD

Installed using the doc link [Install harness](https://github.com/actionml/harness/blob/develop/docs/install.md).

## What I'm doing

Steps: 
1.  ``` harness-start ```
3. ``` harness-cli add <path-to-engine-test_ur-json>``` 
2. ``` python3 import_mobile_device_ur_data_by_event_time.py```
3. ``` harness-cli train test_ur```

After performing the 3rd step, I'm getting this error

## Error
```
:01.177 INFO  NettyBlockTransferService - Server created on 192.168.1.2:35773
12:20:01.178 INFO  BlockManager      - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
12:20:01.195 INFO  BlockManagerMaster - Registering BlockManager BlockManagerId(driver, 192.168.1.2, 35773, None)
12:20:01.197 INFO  BlockManagerMasterEndpoint - Registering block manager 192.168.1.2:35773 with 2.1 GB RAM, BlockManagerId(driver, 192.168.1.2, 35773, None)
12:20:01.200 INFO  BlockManagerMaster - Registered BlockManager BlockManagerId(driver, 192.168.1.2, 35773, None)
12:20:01.200 INFO  BlockManager      - Initialized BlockManager: BlockManagerId(driver, 192.168.1.2, 35773, None)
12:20:01.208 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@706874a{/metrics/json,null,AVAILABLE,@Spark}
12:20:01.251 INFO  URAlgorithm       - Engine-id: test_ur. Spark context spark.submit.deployMode: client
12:20:01.262 WARN  SparkContext      - Using an existing SparkContext; some configuration may not take effect.
12:20:01.468 INFO  MemoryStore       - Block broadcast_0 stored as values in memory (estimated size 8.6 KB, free 2.1 GB)
12:20:01.630 INFO  MemoryStore       - Block broadcast_0_piece0 stored as bytes in memory (estimated size 2.0 KB, free 2.1 GB)
12:20:01.632 INFO  BlockManagerInfo  - Added broadcast_0_piece0 in memory on 192.168.1.2:35773 (size: 2.0 KB, free: 2.1 GB)
12:20:01.638 INFO  SparkContext      - Created broadcast 0 from broadcast at MongoSpark.scala:542
12:20:01.801 INFO  SharedState       - Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/home/dinesh/ml/harness/harnesscli/harness-cli/examples/spark-warehouse').
12:20:01.802 INFO  SharedState       - Warehouse path is 'file:/home/dinesh/ml/harness/harnesscli/harness-cli/examples/spark-warehouse'.
12:20:01.810 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@1593bae9{/SQL,null,AVAILABLE,@Spark}
12:20:01.810 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@4c840fc7{/SQL/json,null,AVAILABLE,@Spark}
12:20:01.811 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@47ca1b15{/SQL/execution,null,AVAILABLE,@Spark}
12:20:01.812 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@4a0406b{/SQL/execution/json,null,AVAILABLE,@Spark}
12:20:01.814 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@5a20d5fd{/static/sql,null,AVAILABLE,@Spark}
12:20:02.091 INFO  StateStoreCoordinatorRef - Registered StateStoreCoordinator endpoint
12:20:02.096 WARN  SparkSession$Builder - Using an existing SparkSession; some configuration may not take effect.
12:20:02.100 INFO  MemoryStore       - Block broadcast_1 stored as values in memory (estimated size 8.7 KB, free 2.1 GB)
12:20:02.126 INFO  MemoryStore       - Block broadcast_1_piece0 stored as bytes in memory (estimated size 2.0 KB, free 2.1 GB)
12:20:02.126 INFO  BlockManagerInfo  - Added broadcast_1_piece0 in memory on 192.168.1.2:35773 (size: 2.0 KB, free: 2.1 GB)
12:20:02.127 INFO  SparkContext      - Created broadcast 1 from broadcast at MongoSpark.scala:542
12:20:02.129 INFO  URPreparator$     - Indicators: List(purchase, view, category-pref, addtocart, transaction)
12:20:02.192 INFO  cluster           - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
12:20:02.201 INFO  cluster           - Cluster description not yet available. Waiting for 30000 ms before timing out
12:20:02.204 INFO  connection        - Opened connection [connectionId{localValue:3, serverValue:7}] to localhost:27017
12:20:02.205 INFO  cluster           - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 1]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=602758}
12:20:02.206 INFO  MongoClientCache  - Creating MongoClient: [localhost:27017]
12:20:02.215 INFO  connection        - Opened connection [connectionId{localValue:4, serverValue:8}] to localhost:27017
12:20:02.250 ERROR URAlgorithm       - Spark computation failed for engine test_ur with params {{"engineId":"test_ur","engineFactory":"com.actionml.engines.ur.UREngine","sparkConf":{"master":"local","spark.driver-memory":"4g","spark.executor-memory":"4g"},"algorithm":{"indicators":[{"name":"purchase"},{"name":"view","maxCorrelatorsPerItem":50},{"name":"category-pref","maxCorrelatorsPerItem":50,"minLLR":5.0},{"name":"addtocart"},{"name":"transaction"}],"num":4}}}
java.lang.IllegalArgumentException: null
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:449)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:432)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:432)
        at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:262)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:261)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:261)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2073)
        at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1364)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.take(RDD.scala:1337)
        at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply$mcZ$sp(RDD.scala:1472)
        at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1472)
        at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1472)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.isEmpty(RDD.scala:1471)
        at com.actionml.engines.ur.URPreparator$$anonfun$8.apply(URPreparator.scala:58)
        at com.actionml.engines.ur.URPreparator$$anonfun$8.apply(URPreparator.scala:58)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:267)
        at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
        at com.actionml.engines.ur.URPreparator$.mkTraining(URPreparator.scala:58)
        at com.actionml.engines.ur.URAlgorithm$$anonfun$train$1.apply(URAlgorithm.scala:262)
        at com.actionml.engines.ur.URAlgorithm$$anonfun$train$1.apply(URAlgorithm.scala:256)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:20:02.256 INFO  SparkContextSupport$ - Job 63becf80-4c6c-4cd4-9181-e0ffa278f37c completed in 1572591002256 ms [engine test_ur]
12:20:02.258 ERROR MongoAsyncDao     - Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(63becf80-4c6c-4cd4-9181-e0ffa278f37c)))
12:20:02.259 ERROR MongoAsyncDao     - Sync DAO error
java.lang.RuntimeException: Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(63becf80-4c6c-4cd4-9181-e0ffa278f37c)))
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:135)
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:129)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
12:20:02.263 INFO  AbstractConnector - Stopped Spark@7cd51c26{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
12:20:02.265 INFO  SparkUI           - Stopped Spark web UI at http://192.168.1.2:4040
12:20:02.266 ERROR AsyncEventQueue   - Listener JobManagerListener threw an exception
java.lang.RuntimeException: Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(63becf80-4c6c-4cd4-9181-e0ffa278f37c)))
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:135)
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:129)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

Here is the data that i've of 'events' in mongodb

```
{ "_id" : ObjectId("5dbabcf41b62a3803294ace9"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "iPhone XS", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-28T18:04:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acec"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "iPhone XR", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-27T22:52:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acee"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "iPhone 8", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-27T03:40:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acf0"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "iPad Pro", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-26T08:28:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acf2"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "U 2", "targetEntityId" : "Pixel Slate", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-25T13:16:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acf4"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "U 2", "targetEntityId" : "Galaxy 8", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-24T18:04:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acf6"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-3", "targetEntityId" : "Surface Pro", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-23T22:52:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acf8"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-4", "targetEntityId" : "iPhone XR", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-23T03:40:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acfa"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-4", "targetEntityId" : "iPhone XR", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-22T08:28:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acfc"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-4", "targetEntityId" : "iPhone XR", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-21T13:16:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294acfe"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-4", "targetEntityId" : "iPhone XR", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-20T18:04:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad00"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-4", "targetEntityId" : "iPhone 8", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-19T22:52:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad02"), "eventId" : null, "event" : "purchase", "entityType" : "user", "entityId" : "u-4", "targetEntityId" : "Galaxy 8", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-19T03:40:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad04"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Phones", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-18T08:28:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad06"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Phones", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-17T13:16:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad08"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Phones", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-16T18:04:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad0a"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Phones", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-15T22:52:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad0c"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Phones", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-15T03:40:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad0e"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Phones", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-14T08:28:36.518Z") }
{ "_id" : ObjectId("5dbabcf41b62a3803294ad10"), "eventId" : null, "event" : "view", "entityType" : "user", "entityId" : "u1", "targetEntityId" : "Mobile-acc", "dateProps" : {  }, "categoricalProps" : {  }, "floatProps" : {  }, "booleanProps" : {  }, "eventTime" : ISODate("2019-10-13T13:16:36.518Z") }

```

Is this error occuring because the 'eventId' is null ?

**Comment by pferrel** [comment]
@singh-dinesh I think this is no longer and issue.

**Comment by pi19404** [comment]
i am getting a similar issue while training , though i am inserting training data and it is reflecting in mongo do , it is not being picked up by spark service it gives me the error No users with indicator: <usage> . how did you end up resolving the issue

**Comment by skarpi** [comment]
@pi19404, not the original poster but I solved this by installing Java 8 and making sure that was used.
