### ISSUE TITLE
Can't set item properties

### ISSUE THREAD

**Issue by sonyshchuk** [actionml/harness#219]
Hello,

I have installed harness via docker-compose and went through https://actionml.com/docs/h_ur_quickstart tutorial step by step.

Right now I have UR engine up and running and I can receive recommendations for a user.

Now I'm trying to set item properties and receiving the error "ERROR URDataset - Can't parse UREvent from JObject".

Full error message:
`
14:11:19.419 INFO  ActorSystemImpl   - Harness Server: HttpRequest(HttpMethod(POST),
http://0.0.0.0:9090/engines/movie_fit/events,
List(Accept: application/json, User-Agent: rest-client/2.1.0 (darwin19.0.0 x86_64) ruby/2.6.5p114, Accept-Encoding: gzip, deflate;q=0.6, identity;q=0.3, Host: 0.0.0.0:9090, Timeout-Access: <function1>),HttpEntity.Strict(application/json,{"event":"$set","entityType":"item","entityId":"1","properties":{"title_type":["movie"],"genres":["4","5"],"persons":["37","1","2","3","4","5","6","7","8","9"]}}),HttpProtocol(HTTP/1.1))
14:11:19.424 ERROR URDataset         - Can't parse UREvent from JObject(List((event,JString($set)), (entityType,JString(item)), (entityId,JString(1)), (properties,JObject(List((title_type,JArray(List(JString(movie)))), (genres,JArray(List(JString(4), JString(5)))), (persons,JArray(List(JString(37), JString(1), JString(2), JString(3), JString(4), JString(5), JString(6), JString(7), JString(8), JString(9)))))))))
org.json4s.package$MappingException: Can't convert JNothing to class java.lang.String
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:403)
	at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:400)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:600)
	at org.json4s.Extraction$.extract(Extraction.scala:387)
	at org.json4s.Extraction$.extract(Extraction.scala:39)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at com.actionml.core.validate.JsonSupport$DateReader$.read(JsonSupport.scala:44)
	at com.actionml.core.validate.JsonSupport$DateReader$.read(JsonSupport.scala:42)
	at org.json4s.ExtractableJsonAstNode.as(ExtractableJsonAstNode.scala:74)
	at com.actionml.engines.ur.URDataset.com$actionml$engines$ur$URDataset$$toUrEvent(URDataset.scala:238)
	at com.actionml.engines.ur.URDataset$$anonfun$input$1.apply(URDataset.scala:98)
	at com.actionml.engines.ur.URDataset$$anonfun$input$1.apply(URDataset.scala:98)
	at cats.data.Validated.andThen(Validated.scala:197)
	at com.actionml.engines.ur.URDataset.input(URDataset.scala:98)
	at com.actionml.engines.ur.UREngine$$anonfun$2.apply(UREngine.scala:113)
	at com.actionml.engines.ur.UREngine$$anonfun$2.apply(UREngine.scala:113)
	at cats.data.Validated.andThen(Validated.scala:197)
	at com.actionml.engines.ur.UREngine.input(UREngine.scala:113)
	at com.actionml.router.service.EventServiceImpl$$anonfun$receive$1.applyOrElse(EventService.scala:47)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at com.actionml.router.service.EventServiceImpl.aroundReceive(EventService.scala:35)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
14:11:19.426 INFO  UREngine          - Engine-id: movie_fit. Bad input  Whoops, no response string 
14:11:19.430 INFO  ActorSystemImpl   - Harness Server: Response for`

Please assist.

**Comment by sonyshchuk** [comment]
I fixed it by creating a new engine with correct spark configuration:

```
"sparkConf": {
    "es.index.auto.create": "true",
    "es.nodes": "elasticsearch",
    "es.nodes.wan.only": "true",
    "master": "local",
    "spark.driver.memory": "1g",
    "spark.es.index.auto.create": "true",
    "spark.es.nodes": "elasticsearch",
    "spark.es.nodes.wan.only": "true",
    "spark.executor.memory": "1g",
    "spark.kryo.referenceTracking": "false",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryoserializer.buffer": "300m",
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
  }
```
