### ISSUE TITLE
Exception on $delete event if id does not exist

### ISSUE THREAD

**Issue by rschuil** [actionml/harness#279]
When sending a $delete event with an entity ID that does not exist, Harness returns status 500 and logs an exception:

09:28:02.279 INFO  ActorSystemImpl   - Harness Server: HttpRequest(HttpMethod(POST),http://host:9090/engines/ur/events,List(Host: host:9090, User-Agent: agent, Timeout-Access: <function1>),HttpEntity.Strict(application/json,{"event":"$delete","entityType":"item","entityId":"766559","eventTime":"2020-10-21T10:28:02+03:00"}),HttpProtocol(HTTP/1.1))
09:28:02.281 ERROR MongoAsyncDao     - Can't removeOne from collection ur.items with filter WrappedArray((_id,Equals(766559)))
09:28:02.282 ERROR ActorSystemImpl   - Internal error
java.lang.RuntimeException: Can't removeOne from collection ur.items with filter WrappedArray((_id,Equals(766559)))
	at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$2.apply(MongoAsyncDao.scala:133)
	at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$2.apply(MongoAsyncDao.scala:127)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  Request : HttpRequest(HttpMethod(POST),http://host:9090/engines/ur/events,List(Host: host:9090, User-Agent: agent, Timeout-Access: <function1>),HttpEntity.Strict(application/json,{"event":"$delete","entityType":"item","entityId":"766559","eventTime":"2020-10-21T10:28:02+03:00"}),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(text/plain; charset=UTF-8,There was an internal server error.),HttpProtocol(HTTP/1.1)))
09:28:02.282 INFO  ActorSystemImpl   - Complete: HttpMethod(POST):http://host:9090/engines/ur/events -> 500 Internal Server Error [3 ms.]

**Comment by frutik** [comment]
:scream_cat:
