### ISSUE TITLE
Unable to train model

### ISSUE THREAD

**Issue by pnutmath** [actionml/harness#301]
I am getting below errors while initiating the jobs to train model.

Harness and Harness CLI is deployed through docker in kubernetes cluster.
Spark master is setup on EC2 with StandaloneMode
Workers are connected to Spark and deployed on kubernets.
Elasticsearch is also in kubernetes.

**Engine config:** 
```json
{
        "engineId": "engine01",
        "engineFactory": "com.actionml.engines.ur.UREngine",
        "sparkConf": {
            "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
            "master": "spark://master:7077",
            "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
            "spark.driver.memory": "3g",
            "spark.es.nodes.wan.only": "true",
            "spark.kryo.referenceTracking": "false",
            "spark.kryoserializer.buffer": "300m",
            "spark.es.index.auto.create": "true",
            "spark.executor.memory": "3g"
        },
        "algorithm": {
            "indicators": [
                {
                    "name": "like"
                },
                {
                    "name": "unlike"
                },
                {
                    "name": "viewed"
                },
                {
                    "name": "posted"
                }
            ]
        }
    },
```

**Errors:**

```
06:30:47.056 INFO  StandaloneAppClient$ClientEndpoint - Connecting to master spark://master:7077...
06:30:47.059 INFO  TransportClientFactory - Successfully created connection to /master:7077 after 2 ms (0 ms spent in bootstraps)
06:31:07.056 INFO  StandaloneAppClient$ClientEndpoint - Connecting to master spark://master:7077...
06:31:27.056 INFO  StandaloneAppClient$ClientEndpoint - Connecting to master spark://master:7077...
06:31:47.056 WARN  StandaloneSchedulerBackend - Application ID is not initialized yet.
06:31:47.056 ERROR StandaloneSchedulerBackend - Application has been killed. Reason: All masters are unresponsive! Giving up.
06:31:47.058 INFO  AbstractConnector - Stopped Spark@31ec0193{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
06:31:47.059 INFO  SparkUI           - Stopped Spark web UI at http://core-harness-main-srvr-dply-85dd94b47f-npvbx:4040
06:31:47.060 INFO  Utils             - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46411.
06:31:47.060 INFO  NettyBlockTransferService - Server created on core-harness-main-srvr-dply-85dd94b47f-npvbx:46411
06:31:47.060 INFO  StandaloneSchedulerBackend - Shutting down all executors
06:31:47.060 INFO  BlockManager      - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
06:31:47.060 INFO  CoarseGrainedSchedulerBackend$DriverEndpoint - Asking each executor to shut down
06:31:47.060 INFO  BlockManagerMaster - Registering BlockManager BlockManagerId(driver, core-harness-main-srvr-dply-85dd94b47f-npvbx, 46411, None)
06:31:47.060 WARN  StandaloneAppClient$ClientEndpoint - Drop UnregisterApplication(null) because has not yet connected to master
06:31:47.061 INFO  BlockManagerMasterEndpoint - Registering block manager core-harness-main-srvr-dply-85dd94b47f-npvbx:46411 with 140.1 MB RAM, BlockManagerId(driver, core-harness-main-srvr-dply-85dd94b47f-npvbx, 46411, None)
06:31:47.061 INFO  MapOutputTrackerMasterEndpoint - MapOutputTrackerMasterEndpoint stopped!
06:31:47.062 INFO  BlockManagerMaster - Registered BlockManager BlockManagerId(driver, core-harness-main-srvr-dply-85dd94b47f-npvbx, 46411, None)
06:31:47.062 INFO  BlockManager      - Initialized BlockManager: BlockManagerId(driver, core-harness-main-srvr-dply-85dd94b47f-npvbx, 46411, None)
06:31:47.063 INFO  ContextHandler    - Started o.s.j.s.ServletContextHandler@4116a948{/metrics/json,null,AVAILABLE,@Spark}
06:31:47.067 INFO  MemoryStore       - MemoryStore cleared
06:31:47.067 INFO  BlockManager      - BlockManager stopped
06:31:47.067 ERROR SparkContext      - Error initializing SparkContext.
java.lang.NullPointerException: null
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:559)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:132)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:119)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
06:31:47.067 INFO  SparkContext      - SparkContext already stopped.
06:31:47.067 INFO  BlockManagerMaster - BlockManagerMaster stopped
06:31:47.067 ERROR AsyncEventQueue   - Listener AppStatusListener threw an exception
java.lang.NullPointerException: null
	at org.apache.spark.status.AppStatusListener.onApplicationEnd(AppStatusListener.scala:157)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:57)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:91)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:83)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1323)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:82)
06:31:47.067 ERROR SparkContextSupport$ - Spark context can not be created for job JobDescription(f3abfe3d-d1a9-4e35-a86f-5ac30abd0640,queued,Spark job,Some(Wed May 05 06:30:46 GMT 2021),None)
java.lang.NullPointerException: null
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:559)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:132)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:119)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
06:31:47.069 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint - OutputCommitCoordinator stopped!
06:31:47.072 INFO  JobManager$       - Job f3abfe3d-d1a9-4e35-a86f-5ac30abd0640 marked as failed
06:31:47.072 INFO  SparkContext      - Successfully stopped SparkContext
```

**Comment by pnutmath** [comment]
There was mismatch of version harness using Spark 2 client while I have deploy Spark 3 cluster
